---
name: 'run-mage'

on:  # yamllint disable-line rule:truthy
  push:
  workflow_dispatch:

jobs:
  mage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          cache: false
      - uses: magefile/mage-action@v2
        with:
          version: latest
          args: -l
      - uses: magefile/mage-action@v2
        with:
          version: latest
          args: before
      - uses: magefile/mage-action@v2
        with:
          version: latest
          args: "-v all"
